name: acme

config-version: 2
version: '0.1'

profile: playbook

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  playbook:
    materialized: table
    stging:
      materialized: view
  # transient: true

